server:
  port: 3367

eureka:
  instance:
    instance-id: configclient3367
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

self:
  foobar: foouat